name: helper
description: "A new Flutter package project."
version: 0.0.1
# homepage:
publish_to: none
environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.2
  freezed_annotation: ^2.4.4
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.19.0
  jserializer:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: jserializer/
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  provider: ^6.1.5
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  jserializer_generator:
    git:
      url: https://github.com/erabti/jserializer_library.git
      path: jserializer_generator/
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  generate: true
